harryfei/which-rs

Cargo.toml
src/lib.rs

Hi there! I needed the functionality of this crate in [a project I'm working on](https://github.com/luser/sccache2), but I needed it to do a few more things above what your crate currently provides. I wrote my own implementation that met my needs, but I think it'd be great if I could just have my project use your crate instead.
I tried to split my changes up into smaller commits, hopefully that makes them easier to understand.
The changes are, in order:
1. Change binary_name parameter to `AsRef<OsStr>`. This lets callers pass in anything that can be taken as an `&OsStr`, so you can pass any of `&str`, `String`, `OsString`, `Path`.
2. Don't return non-executable files. This matches the behavior of the `which` command on POSIX systems. I pulled in the `libc` crate to call `libc::access` for …

Make which more featureful, add a lot more tests

---

src/lib.rs

If I compile master, I get:
```
error[E0599]: no method named `eq_ignore_ascii_case` found for type `&str` in the current scope
--> /home/symphorien/.cargo/registry/src/github.com-1ecc6299db9ec823/which-1.0.4/src/lib.rs:37:24
|
37 |             .map(|e| e.eq_ignore_ascii_case(env::consts::EXE_EXTENSION)) {
|                        ^^^^^^^^^^^^^^^^^^^^
|
= help: items from traits can only be used if the trait is in scope
= note: the following trait is implemented but not in scope, perhaps add a `use` for it:
candidate #1: `use std::ascii::AsciiExt;`
error: aborting due to previous error
error: Could not compile `which`.
```
Using the tip of the compiler, here is a fix :)
Tests still pass.
Please release a new version on crates.io after merging :)

add forgotten `use std::ascii::AsciiExt;`

---

Cargo.toml
src/lib.rs

Hi I have a PR here with the intent to have `which-rs` play nice with `failure` crate, need to check if you willing to accept the PR. The changes are as below:
* Change API to return struct instead of `'static str` as error
* Implement `Error` trait for the new struct
* Unit test to include compilation test for `failure` crate usage
* Apply `cargo fmt` and fix `cargo clippy` issues
* Bump version to `2.0.0` due to API changes

Implement Error trait for Failure usage

---

Cargo.toml
src/error.rs
src/lib.rs

This allows crates to use `which` without being "infected" by `libproc_macro`, as described here:
https://github.com/rust-lang/rust-bindgen/issues/1407#issuecomment-436057854

Use failure without its derive feature

---

src/error.rs
src/lib.rs
tests/basic.rs

This is something I've worked on in a potential downstream crate, but I think it's best suited for `which-rs`. I'm happy to consider naming suggestions.

Add which::Path, which::CanonicalPath structs

---

.travis.yml
Cargo.toml
appveyor.yml
src/error.rs
src/lib.rs
tests/basic.rs

While being compatible with `failure` is nice, the way it is currently done in this library forces the dependency on all users of this crate, even if they do not use it at all.
The biggest example of this issue is `bindgen`, the biggest dependent of this crate but which does not use `failure`, hence making everybody that uses `bindgen` depend on `failure` (and all its dependencies) for pretty much nothing.
This PR makes the dependency on `failure` optional, by creating a new `use_failure` feature that controls whether or not the dependency on `failure` is enabled.
This feature is enabled by default to avoid any breaking changes, but it can be disabled by any dependent crate that does not wish to use `failure` and can get rid of the extra dependency.
The CI configurations were also …

Make dependency on "failure" optional

---

src/error.rs

I'm personally not a fan of using `failure` in *libraries*. Since it breaks the ecosystem into those who expose `Fail` errors and those who expose `std::error::Error` errors. Now when `failure` is optional here, it was very easy to add support for making the `which` error type a standard error.

Implement std::error::Error when not using failure

---

Cargo.toml
README.md
src/error.rs
src/lib.rs
tests/basic.rs

Optional dependencies automatically becomes a feature with the same name as that dependency. So it can be used instead of creating an arbitrary extra feature, and is IMO more idiomatic.
Strictly technically speaking this PR is a breaking change. But in practice I doubt it would break any existing code. It just renames a feature that is activated by default. So for people with the defaults they won't notice. And people deactivating default features hopefully never activated `use_failure` again, since that would simply just bring them back to where they started.

Use automatic failure feature instead of redundant use_failure

---

Cargo.toml
README.md
src/error.rs
src/finder.rs
src/lib.rs
tests/basic.rs

As per discussion in https://github.com/harryfei/which-rs/issues/20, the more rustic way of representing errors and results is using `std::error::Error` and `std::result::Result` which is incompatible with the use of `failure`. This PR removes `failure` and replaces the old `ErrorKind` with the `Error` enum for which `std::error::Error` is derived using `thiserror`. This greatly simplifies error handling from a user's perspective.
Since this does modify the library's user-facing public members in a backwards-incompatible way. I would recommend the next release should have its major version number bumped after this is merged.

replace failure with std::error:Error and thiserror

---

src/checker.rs

Info
-----
The fix to support Windows Reparse Points in #23 inadvertently resulted in actual Windows symlinks being skipped. Since `fs::symlink_metadata` doesn't traverse symlinks, calling it on a symlink will result in `is_file` being false, cause `which` to incorrectly ignore the symlink.
Changes
-----
* Added an additional check for `is_symlink` in the Windows branch of the `ExistedChecker`, which correctly includes actual symlinks as well as potentially executable.
Tested
-----
* Created a symlink to a `.exe` file locally (following [these steps](https://winaero.com/blog/create-symbolic-link-windows-10-powershell/)) and confirmed that this change can detect the linked executable.
* Created a symlink to a directory and confirmed that `which` still correctly detects directories aren't …

Support symlinked executables on Windows

---

Cargo.toml
src/error.rs
src/lib.rs

Manually implement `std::error::Error` and `std::fmt::Display` for the `Error` enum, rather than using the derived implementation from `thiserror`.
This should provide a compile time benefit, especially on slow machines.

Remove thiserror crate

---

.gitignore
Cargo.toml
src/finder.rs
src/lib.rs
tests/basic.rs

This PR adds an optional feature to look for binaries that match a given regular expression.
**Notes**
- It's only possible to look inside a provided list of paths, and using a `/` in the regular expression won't search in the current directory.
- I'm not sure if I have enough tests. If anything is missing, please let me know!
Fixes: #39

Allow searching with regular expressions

---

src/finder.rs

The import was necessary when using the regex feature.
Fixes:  #41

Import std::fs with the regex feature

---

Cargo.toml
README.md
src/finder.rs
src/lib.rs
tests/basic.rs

Add documentation for the regex path search feature.
Also accept `&Regex` in addition to just `Regex`.
Related to #37 and #40.

Documentation for regex feature

---

.github/workflows/rust.yml
src/checker.rs
src/finder.rs
tests/basic.rs

Running the `clippy` linter does not make much sense if 99% of its coverage isn't stopping the CI from succeeding.

ci: Disallow warnings from `clippy`

---

Cargo.toml
tests/basic.rs

As the tempdir crate have been superceded by tempfile

Replace tempdir with tempfile

---

Cargo.toml
src/finder.rs
src/lib.rs

This change has _not_ been run-tested, only build-tested in a crosscompiled environment.
---
Piggybacking on the [motivation in winit]: `lazy_static!` is a macro whereas `once_cell` achieves the same using generics.  Its implementation has also been [proposed for inclusion in `std`], making it easier to switch to a standardized version if/when that happens.  The author of that winit PR is making this change to many more crates, slowly turning the scales in favour of `once_cell` in most dependency trees.  Furthermore `lazy_static` hasn't published any updates for 3 years.
See also [the `once_cell` F.A.Q.].
[motivation in winit]: https://github.com/rust-windowing/winit/pull/2313
[proposed for inclusion in `std`]: https://github.com/rust-lang/rust/issues/74465
[the `once_cell` F.A.Q.]: …

Replace ancient `lazy_static` crate with `once_cell`

---

Cargo.toml
src/finder.rs
tests/basic.rs

Fixes #71 by expanding tilde (~) to the value of the home directory. Emulates the bash approach to tilde expansion.
This PR intentionally ignores the more complicated parts of how `bash` expands the tilde character, because I feel that path resolution using the PATH environment variable should not rely on any information about the current directory, or about the previous current directory. So, `~/dir` works, `~+/dir` does not.

Implement tilde expansion for path env

---

Cargo.toml
src/checker.rs
src/lib.rs
tests/basic.rs

This commit replaces the code using libc with equivalent code using rustix. In addition to safety, this move also removes the dependency on C code and replaces it with a syscall, which is much faster.
This PR also adds `forbid(unsafe_code)`, so that this crate shows up as unsafe-free when processed in `cargo-geiger`.

Switch to rustix from libc

---

CHANGELOG.md
Cargo.toml
src/finder.rs

remove dependency on once_cell

---

.github/workflows/rust.yml
Cargo.toml
deny.toml
src/checker.rs
src/finder.rs

This also moves `regex` into a proper feature.
Fixes #95

Add optional tracing feature, trace which logic

---

Cargo.toml
src/finder.rs

Switch to `env_home` crate

---

Cargo.toml
src/finder.rs

Adding a proper error path here would be breaking API change, however we can pass through the tilde unaltered to avoid picking up an unintended binary.

fixes #106, bump patch version

---

src/finder.rs
tests/basic.rs

Previously, when you would try to find `./bin` somewhere that's in your cwd, `which` would return a file like this:
```
/path/to/./bin
```
where the `.` is not something you would expect to find, while technically valid.

When searching for `./script.sh`, don't return `/path/to/./script.sh`

---

Cargo.toml
src/lib.rs

This PR bumps rustix to the 1.0 stable release. rustix 1.0 has an MSRV of 1.63 at the moment, below this crate.
Thank you for maintaining `which-rs`! 😃

Bump rustix version
